//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaBDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int id { get; set; }
        public int IdClaseArticulo { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
    
        public virtual ClaseArticulo ClaseArticulo { get; set; }
    }
}
