CREATE TABLE Usuario
(
	id INT IDENTITY (1, 1) PRIMARY KEY NOT NULL
	, UserName VARCHAR(16) NOT NULL
	, Password VARCHAR(16)  NOT NULL
);

CREATE TABLE ClaseArticulo
(
	id INT IDENTITY (1, 1) PRIMARY KEY NOT NULL
	, Nombre VARCHAR(64) NOT NULL
);

CREATE TABLE Articulo 
(
	id INT IDENTITY (1, 1) PRIMARY KEY NOT NULL
	, IdClaseArticulo INT FOREIGN KEY REFERENCES ClaseArticulo (id) NOT NULL
	, Nombre VARCHAR(128) NOT NULL
	, Precio MONEY NOT NULL
);